---
- name: Create data directory
  file:
    path: "{{ hadoop_home }}/{{ datanode_data_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: Create datanode unit
  template:
    src: templates/datanode.service.j2
    dest: /etc/systemd/system/datanode.service
  notify:
    - datanode start

- name: Copy config files
  template:
    src: templates/hdfs-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/hdfs-site.xml"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  notify:
    - datanode restart
