---
- name: format namenode dir
  shell: "export JAVA_HOME={{ java_home }}; {{ hadoop_dir }}/bin/hdfs namenode -format"
  args:
    executable: /bin/bash

- name: namenode start
  systemd:
    name: namenode
    daemon_reload: yes
    enabled: yes
    state: started

- name: namenode restart
  systemd:
    name: namenode
    state: restarted
