
---
- name: Create name directory
  file:
    path: "{{ hadoop_home }}/{{ namenode_name_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  notify:
    - format namenode dir

- name: Create namenode unit
  template:
    src: templates/namenode.service.j2
    dest: /etc/systemd/system/namenode.service
  notify:
    - namenode start

- name: Copy config files
  template:
    src: templates/hdfs-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/hdfs-site.xml"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
